# Generated by Django 5.0.4 on 2024-04-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=255)),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
    ]
