# Generated by Django 5.0.6 on 2024-06-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options'),
    ]

    operations = [
    ]
